var hierarchy =
[
    [ "__DMA_HandleTypeDef", "struct____DMA__HandleTypeDef.html", null ],
    [ "__iar_u32", "struct____iar__u32.html", null ],
    [ "__UART_HandleTypeDef", "struct____UART__HandleTypeDef.html", null ],
    [ "ADC_Common_TypeDef", "structADC__Common__TypeDef.html", null ],
    [ "ADC_TypeDef", "structADC__TypeDef.html", null ],
    [ "APSR_Type", "unionAPSR__Type.html", null ],
    [ "ARM_MPU_Region_t", "structARM__MPU__Region__t.html", null ],
    [ "CommandLineArguments", "classCommandLineArguments.html", null ],
    [ "CommandLineTestRunner", "classCommandLineTestRunner.html", null ],
    [ "COMP_TypeDef", "structCOMP__TypeDef.html", null ],
    [ "CONTROL_Type", "unionCONTROL__Type.html", null ],
    [ "CORDIC_TypeDef", "structCORDIC__TypeDef.html", null ],
    [ "CoreDebug_Type", "structCoreDebug__Type.html", null ],
    [ "cpputest_longlong", "structcpputest__longlong.html", null ],
    [ "cpputest_ulonglong", "structcpputest__ulonglong.html", null ],
    [ "CppUTestFailedException", "classCppUTestFailedException.html", null ],
    [ "CRC_TypeDef", "structCRC__TypeDef.html", null ],
    [ "CRS_TypeDef", "structCRS__TypeDef.html", null ],
    [ "DAC_TypeDef", "structDAC__TypeDef.html", null ],
    [ "DBGMCU_TypeDef", "structDBGMCU__TypeDef.html", null ],
    [ "DMA_Channel_TypeDef", "structDMA__Channel__TypeDef.html", null ],
    [ "DMA_InitTypeDef", "structDMA__InitTypeDef.html", null ],
    [ "DMA_TypeDef", "structDMA__TypeDef.html", null ],
    [ "DMAMUX_Channel_TypeDef", "structDMAMUX__Channel__TypeDef.html", null ],
    [ "DMAMUX_ChannelStatus_TypeDef", "structDMAMUX__ChannelStatus__TypeDef.html", null ],
    [ "DMAMUX_RequestGen_TypeDef", "structDMAMUX__RequestGen__TypeDef.html", null ],
    [ "DMAMUX_RequestGenStatus_TypeDef", "structDMAMUX__RequestGenStatus__TypeDef.html", null ],
    [ "DWT_Type", "structDWT__Type.html", null ],
    [ "ExecFunction", "classExecFunction.html", [
      [ "ExecFunctionWithoutParameters", "classExecFunctionWithoutParameters.html", null ]
    ] ],
    [ "EXTI_ConfigTypeDef", "structEXTI__ConfigTypeDef.html", null ],
    [ "EXTI_HandleTypeDef", "structEXTI__HandleTypeDef.html", null ],
    [ "EXTI_TypeDef", "structEXTI__TypeDef.html", null ],
    [ "FDCAN_Config_TypeDef", "structFDCAN__Config__TypeDef.html", null ],
    [ "FDCAN_GlobalTypeDef", "structFDCAN__GlobalTypeDef.html", null ],
    [ "FLASH_EraseInitTypeDef", "structFLASH__EraseInitTypeDef.html", null ],
    [ "FLASH_OBProgramInitTypeDef", "structFLASH__OBProgramInitTypeDef.html", null ],
    [ "FLASH_ProcessTypeDef", "structFLASH__ProcessTypeDef.html", null ],
    [ "FLASH_TypeDef", "structFLASH__TypeDef.html", null ],
    [ "FMAC_TypeDef", "structFMAC__TypeDef.html", null ],
    [ "FMC_Bank1_TypeDef", "structFMC__Bank1__TypeDef.html", null ],
    [ "FMC_Bank1E_TypeDef", "structFMC__Bank1E__TypeDef.html", null ],
    [ "FMC_Bank3_TypeDef", "structFMC__Bank3__TypeDef.html", null ],
    [ "FPU_Type", "structFPU__Type.html", null ],
    [ "GlobalMemoryAccountant", "classGlobalMemoryAccountant.html", null ],
    [ "GlobalMemoryAllocatorStash", "classGlobalMemoryAllocatorStash.html", null ],
    [ "GlobalSimpleStringAllocatorStash", "classGlobalSimpleStringAllocatorStash.html", null ],
    [ "GlobalSimpleStringCache", "classGlobalSimpleStringCache.html", null ],
    [ "GlobalSimpleStringMemoryAccountant", "classGlobalSimpleStringMemoryAccountant.html", null ],
    [ "GPIO_InitTypeDef", "structGPIO__InitTypeDef.html", null ],
    [ "GPIO_TypeDef", "structGPIO__TypeDef.html", null ],
    [ "GTestConvertor", "classGTestConvertor.html", null ],
    [ "GTestFlagsThatAllocateMemory", "classGTestFlagsThatAllocateMemory.html", null ],
    [ "HAL_DMA_MuxRequestGeneratorConfigTypeDef", "structHAL__DMA__MuxRequestGeneratorConfigTypeDef.html", null ],
    [ "HAL_DMA_MuxSyncConfigTypeDef", "structHAL__DMA__MuxSyncConfigTypeDef.html", null ],
    [ "HRTIM_Common_TypeDef", "structHRTIM__Common__TypeDef.html", null ],
    [ "HRTIM_Master_TypeDef", "structHRTIM__Master__TypeDef.html", null ],
    [ "HRTIM_Timerx_TypeDef", "structHRTIM__Timerx__TypeDef.html", null ],
    [ "HRTIM_TypeDef", "structHRTIM__TypeDef.html", null ],
    [ "I2C_TypeDef", "structI2C__TypeDef.html", null ],
    [ "IPSR_Type", "unionIPSR__Type.html", null ],
    [ "ITM_Type", "structITM__Type.html", null ],
    [ "IWDG_TypeDef", "structIWDG__TypeDef.html", null ],
    [ "LPTIM_TypeDef", "structLPTIM__TypeDef.html", null ],
    [ "MemoryAccountant", "classMemoryAccountant.html", null ],
    [ "MemoryLeakDetector", "classMemoryLeakDetector.html", null ],
    [ "MemoryLeakDetectorList", "structMemoryLeakDetectorList.html", null ],
    [ "MemoryLeakDetectorNode", "structMemoryLeakDetectorNode.html", null ],
    [ "MemoryLeakDetectorTable", "structMemoryLeakDetectorTable.html", null ],
    [ "MemoryLeakFailure", "classMemoryLeakFailure.html", null ],
    [ "MemoryLeakOutputStringBuffer", "classMemoryLeakOutputStringBuffer.html", null ],
    [ "MemoryReportFormatter", "classMemoryReportFormatter.html", [
      [ "CodeMemoryReportFormatter", "classCodeMemoryReportFormatter.html", null ],
      [ "NormalMemoryReportFormatter", "classNormalMemoryReportFormatter.html", null ]
    ] ],
    [ "MockActualCall", "classMockActualCall.html", [
      [ "MockActualCallTrace", "classMockActualCallTrace.html", null ],
      [ "MockCheckedActualCall", "classMockCheckedActualCall.html", null ],
      [ "MockIgnoredActualCall", "classMockIgnoredActualCall.html", null ]
    ] ],
    [ "MockExpectedCall", "classMockExpectedCall.html", [
      [ "MockCheckedExpectedCall", "classMockCheckedExpectedCall.html", null ],
      [ "MockIgnoredExpectedCall", "classMockIgnoredExpectedCall.html", null ]
    ] ],
    [ "MockExpectedCallsList", "classMockExpectedCallsList.html", null ],
    [ "MockExpectedCallsList::MockExpectedCallsListNode", "classMockExpectedCallsList_1_1MockExpectedCallsListNode.html", null ],
    [ "MockFailureReporter", "classMockFailureReporter.html", null ],
    [ "MockNamedValue", "classMockNamedValue.html", [
      [ "MockCheckedExpectedCall::MockExpectedFunctionParameter", "classMockCheckedExpectedCall_1_1MockExpectedFunctionParameter.html", null ]
    ] ],
    [ "MockNamedValueComparator", "classMockNamedValueComparator.html", [
      [ "MockFunctionComparator", "classMockFunctionComparator.html", null ]
    ] ],
    [ "MockNamedValueComparatorsAndCopiersRepository", "classMockNamedValueComparatorsAndCopiersRepository.html", null ],
    [ "MockNamedValueCopier", "classMockNamedValueCopier.html", [
      [ "MockFunctionCopier", "classMockFunctionCopier.html", null ]
    ] ],
    [ "MockNamedValueList", "classMockNamedValueList.html", null ],
    [ "MockNamedValueListNode", "classMockNamedValueListNode.html", null ],
    [ "MockCheckedActualCall::MockOutputParametersListNode", "classMockCheckedActualCall_1_1MockOutputParametersListNode.html", null ],
    [ "MockSupport", "classMockSupport.html", null ],
    [ "NVIC_Type", "structNVIC__Type.html", null ],
    [ "OPAMP_TypeDef", "structOPAMP__TypeDef.html", null ],
    [ "OrderedTestInstaller", "classOrderedTestInstaller.html", null ],
    [ "PWR_PVDTypeDef", "structPWR__PVDTypeDef.html", null ],
    [ "PWR_PVMTypeDef", "structPWR__PVMTypeDef.html", null ],
    [ "PWR_TypeDef", "structPWR__TypeDef.html", null ],
    [ "QUADSPI_TypeDef", "structQUADSPI__TypeDef.html", null ],
    [ "RCC_ClkInitTypeDef", "structRCC__ClkInitTypeDef.html", null ],
    [ "RCC_CRSInitTypeDef", "structRCC__CRSInitTypeDef.html", null ],
    [ "RCC_CRSSynchroInfoTypeDef", "structRCC__CRSSynchroInfoTypeDef.html", null ],
    [ "RCC_OscInitTypeDef", "structRCC__OscInitTypeDef.html", null ],
    [ "RCC_PeriphCLKInitTypeDef", "structRCC__PeriphCLKInitTypeDef.html", null ],
    [ "RCC_PLLInitTypeDef", "structRCC__PLLInitTypeDef.html", null ],
    [ "RCC_TypeDef", "structRCC__TypeDef.html", null ],
    [ "RingBuffer", "structRingBuffer.html", null ],
    [ "RNG_TypeDef", "structRNG__TypeDef.html", null ],
    [ "RTC_TypeDef", "structRTC__TypeDef.html", null ],
    [ "SAI_Block_TypeDef", "structSAI__Block__TypeDef.html", null ],
    [ "SAI_TypeDef", "structSAI__TypeDef.html", null ],
    [ "SCB_Type", "structSCB__Type.html", null ],
    [ "SCnSCB_Type", "structSCnSCB__Type.html", null ],
    [ "testing::ScopedFakeTestPartResultReporter", null, [
      [ "GTestDummyResultReporter", "classGTestDummyResultReporter.html", null ],
      [ "GTestResultReporter", "classGTestResultReporter.html", null ]
    ] ],
    [ "ScopedMutexLock", "classScopedMutexLock.html", null ],
    [ "SetBooleanOnDestructorCall", "classSetBooleanOnDestructorCall.html", null ],
    [ "SimpleMutex", "classSimpleMutex.html", null ],
    [ "SimpleString", "classSimpleString.html", null ],
    [ "SimpleStringBuffer", "structSimpleStringBuffer.html", null ],
    [ "SimpleStringCollection", "classSimpleStringCollection.html", null ],
    [ "SimpleStringInternalCache", "classSimpleStringInternalCache.html", null ],
    [ "SMockActualCall_c", "structSMockActualCall__c.html", null ],
    [ "SMockExpectedCall_c", "structSMockExpectedCall__c.html", null ],
    [ "SMockSupport_c", "structSMockSupport__c.html", null ],
    [ "SMockValue_c", "structSMockValue__c.html", null ],
    [ "SPI_TypeDef", "structSPI__TypeDef.html", null ],
    [ "SYSCFG_TypeDef", "structSYSCFG__TypeDef.html", null ],
    [ "SysTick_Type", "structSysTick__Type.html", null ],
    [ "TAMP_TypeDef", "structTAMP__TypeDef.html", null ],
    [ "TestFailure", "classTestFailure.html", [
      [ "BinaryEqualFailure", "classBinaryEqualFailure.html", null ],
      [ "BitsEqualFailure", "classBitsEqualFailure.html", null ],
      [ "CheckEqualFailure", "classCheckEqualFailure.html", null ],
      [ "CheckFailure", "classCheckFailure.html", null ],
      [ "ComparisonFailure", "classComparisonFailure.html", null ],
      [ "ContainsFailure", "classContainsFailure.html", null ],
      [ "DoublesEqualFailure", "classDoublesEqualFailure.html", null ],
      [ "EqualsFailure", "classEqualsFailure.html", null ],
      [ "FailFailure", "classFailFailure.html", null ],
      [ "FeatureUnsupportedFailure", "classFeatureUnsupportedFailure.html", null ],
      [ "LongLongsEqualFailure", "classLongLongsEqualFailure.html", null ],
      [ "LongsEqualFailure", "classLongsEqualFailure.html", null ],
      [ "MockFailure", "classMockFailure.html", [
        [ "MockCallOrderFailure", "classMockCallOrderFailure.html", null ],
        [ "MockExpectedCallsDidntHappenFailure", "classMockExpectedCallsDidntHappenFailure.html", null ],
        [ "MockExpectedObjectDidntHappenFailure", "classMockExpectedObjectDidntHappenFailure.html", null ],
        [ "MockExpectedParameterDidntHappenFailure", "classMockExpectedParameterDidntHappenFailure.html", null ],
        [ "MockNoWayToCompareCustomTypeFailure", "classMockNoWayToCompareCustomTypeFailure.html", null ],
        [ "MockNoWayToCopyCustomTypeFailure", "classMockNoWayToCopyCustomTypeFailure.html", null ],
        [ "MockUnexpectedCallHappenedFailure", "classMockUnexpectedCallHappenedFailure.html", null ],
        [ "MockUnexpectedInputParameterFailure", "classMockUnexpectedInputParameterFailure.html", null ],
        [ "MockUnexpectedObjectFailure", "classMockUnexpectedObjectFailure.html", null ],
        [ "MockUnexpectedOutputParameterFailure", "classMockUnexpectedOutputParameterFailure.html", null ]
      ] ],
      [ "SignedBytesEqualFailure", "classSignedBytesEqualFailure.html", null ],
      [ "StringEqualFailure", "classStringEqualFailure.html", null ],
      [ "StringEqualNoCaseFailure", "classStringEqualNoCaseFailure.html", null ],
      [ "UnsignedLongLongsEqualFailure", "classUnsignedLongLongsEqualFailure.html", null ],
      [ "UnsignedLongsEqualFailure", "classUnsignedLongsEqualFailure.html", null ]
    ] ],
    [ "TestFilter", "classTestFilter.html", null ],
    [ "TestInstaller", "classTestInstaller.html", null ],
    [ "TestMemoryAllocator", "classTestMemoryAllocator.html", [
      [ "AccountingTestMemoryAllocator", "classAccountingTestMemoryAllocator.html", null ],
      [ "CrashOnAllocationAllocator", "classCrashOnAllocationAllocator.html", null ],
      [ "FailableMemoryAllocator", "classFailableMemoryAllocator.html", null ],
      [ "MemoryLeakAllocator", "classMemoryLeakAllocator.html", null ],
      [ "MemoryReportAllocator", "classMemoryReportAllocator.html", null ],
      [ "NullUnknownAllocator", "classNullUnknownAllocator.html", null ],
      [ "SimpleStringCacheAllocator", "classSimpleStringCacheAllocator.html", null ]
    ] ],
    [ "TestOutput", "classTestOutput.html", [
      [ "CompositeTestOutput", "classCompositeTestOutput.html", null ],
      [ "ConsoleTestOutput", "classConsoleTestOutput.html", [
        [ "TeamCityTestOutput", "classTeamCityTestOutput.html", null ]
      ] ],
      [ "JUnitTestOutput", "classJUnitTestOutput.html", null ],
      [ "StringBufferTestOutput", "classStringBufferTestOutput.html", null ]
    ] ],
    [ "TestPlugin", "classTestPlugin.html", [
      [ "IEEE754ExceptionsPlugin", "classIEEE754ExceptionsPlugin.html", null ],
      [ "MemoryLeakWarningPlugin", "classMemoryLeakWarningPlugin.html", null ],
      [ "MemoryReporterPlugin", "classMemoryReporterPlugin.html", null ],
      [ "MockSupportPlugin", "classMockSupportPlugin.html", null ],
      [ "NullTestPlugin", "classNullTestPlugin.html", null ],
      [ "SetPointerPlugin", "classSetPointerPlugin.html", null ]
    ] ],
    [ "TestRegistry", "classTestRegistry.html", null ],
    [ "TestResult", "classTestResult.html", null ],
    [ "TestTerminator", "classTestTerminator.html", [
      [ "GMockTestTerminator", "classGMockTestTerminator.html", null ],
      [ "NormalTestTerminator", "classNormalTestTerminator.html", [
        [ "CrashingTestTerminator", "classCrashingTestTerminator.html", null ]
      ] ],
      [ "TestTerminatorWithoutExceptions", "classTestTerminatorWithoutExceptions.html", null ]
    ] ],
    [ "TestTestingFixture", "classTestTestingFixture.html", null ],
    [ "TIM_Base_InitTypeDef", "structTIM__Base__InitTypeDef.html", null ],
    [ "TIM_BreakDeadTimeConfigTypeDef", "structTIM__BreakDeadTimeConfigTypeDef.html", null ],
    [ "TIM_ClearInputConfigTypeDef", "structTIM__ClearInputConfigTypeDef.html", null ],
    [ "TIM_ClockConfigTypeDef", "structTIM__ClockConfigTypeDef.html", null ],
    [ "TIM_Encoder_InitTypeDef", "structTIM__Encoder__InitTypeDef.html", null ],
    [ "TIM_HallSensor_InitTypeDef", "structTIM__HallSensor__InitTypeDef.html", null ],
    [ "TIM_HandleTypeDef", "structTIM__HandleTypeDef.html", null ],
    [ "TIM_IC_InitTypeDef", "structTIM__IC__InitTypeDef.html", null ],
    [ "TIM_MasterConfigTypeDef", "structTIM__MasterConfigTypeDef.html", null ],
    [ "TIM_OC_InitTypeDef", "structTIM__OC__InitTypeDef.html", null ],
    [ "TIM_OnePulse_InitTypeDef", "structTIM__OnePulse__InitTypeDef.html", null ],
    [ "TIM_SlaveConfigTypeDef", "structTIM__SlaveConfigTypeDef.html", null ],
    [ "TIM_TypeDef", "structTIM__TypeDef.html", null ],
    [ "TIMEx_BreakInputConfigTypeDef", "structTIMEx__BreakInputConfigTypeDef.html", null ],
    [ "TIMEx_EncoderIndexConfigTypeDef", "structTIMEx__EncoderIndexConfigTypeDef.html", null ],
    [ "TPI_Type", "structTPI__Type.html", null ],
    [ "UART_AdvFeatureInitTypeDef", "structUART__AdvFeatureInitTypeDef.html", null ],
    [ "UART_InitTypeDef", "structUART__InitTypeDef.html", null ],
    [ "UART_WakeUpTypeDef", "structUART__WakeUpTypeDef.html", null ],
    [ "UCPD_TypeDef", "structUCPD__TypeDef.html", null ],
    [ "USART_TypeDef", "structUSART__TypeDef.html", null ],
    [ "USB_TypeDef", "structUSB__TypeDef.html", null ],
    [ "Utest", "classUtest.html", [
      [ "ExecFunctionTest", "classExecFunctionTest.html", null ],
      [ "GTestUTest", "classGTestUTest.html", null ]
    ] ],
    [ "UtestShell", "classUtestShell.html", [
      [ "ExecFunctionTestShell", "classExecFunctionTestShell.html", null ],
      [ "GTestShell", "classGTestShell.html", null ],
      [ "IgnoredUtestShell", "classIgnoredUtestShell.html", null ],
      [ "OrderedTestShell", "classOrderedTestShell.html", null ]
    ] ],
    [ "UtestShellPointerArray", "classUtestShellPointerArray.html", null ],
    [ "VREFBUF_TypeDef", "structVREFBUF__TypeDef.html", null ],
    [ "WWDG_TypeDef", "structWWDG__TypeDef.html", null ],
    [ "xPSR_Type", "unionxPSR__Type.html", null ]
];